version: '2'
services:
  writer:
    image: node:7-alpine
    volumes:
    - /tmp/:/data/
    command: node -e "var fs = require('fs'); fs.writeFile('/data/node-test.txt', 'Hey there!', function () {console.log('writing /data/node-test.txt')})"

  reader:
    image: node:7-alpine
    volumes_from:
    - writer
    command: node -e "var fs = require('fs'); fs.readFile('/data/node-test.txt', 'utf8', function (err, data) {console.log(data);});"